# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from dots_python_sdk.apis.path_to_api import path_to_api

import enum


class PathValues(str, enum.Enum):
    V2_USERS = "/v2/users"
    V2_USERS_USER_ID = "/v2/users/{user_id}"
    V2_USERS_USER_ID_COMPLIANCE = "/v2/users/{user_id}/compliance"
    V2_USERS_USER_ID_SENDVERIFICATIONTOKEN = "/v2/users/{user_id}/send-verification-token"
    V2_USERS_USER_ID_VERIFY = "/v2/users/{user_id}/verify"
    V2_USERS_USER_ID_PAYOUTMETHODS = "/v2/users/{user_id}/payout-methods"
    V2_TRANSFERS = "/v2/transfers"
    V2_TRANSFERS_TRANSFER_ID = "/v2/transfers/{transfer_id}"
    V2_FLOWS = "/v2/flows"
    V2_FLOWS_FLOW_ID = "/v2/flows/{flow_id}"
    V2_PAYOUTLINKS = "/v2/payout-links"
    V2_PAYOUTLINKS_PAYOUT_LINK_ID = "/v2/payout-links/{payout_link_id}"
    V2_PAYOUTS = "/v2/payouts"
    V2_PAYMENTS = "/v2/payments"
    V2_PAYOUTS_SENDPAYOUT = "/v2/payouts/send-payout"
    V2_PAYOUTREQUESTS = "/v2/payout-requests"
    V2_PAYOUTREQUESTS_PAYOUT_REQUEST_ID = "/v2/payout-requests/{payout_request_id}"
    V2_TRANSACTIONS = "/v2/transactions"
    V2_TRANSACTIONS_TRANSACTION_ID = "/v2/transactions/{transaction_id}"
    V2_PAYMENTINTENTS = "/v2/payment-intents"
    V2_PAYMENTINTENTS_PAYMENT_INTENT_ID = "/v2/payment-intents/{payment_intent_id}"
    V2_PAYMENTINTENTS_PAYMENT_INTENT_ID_CONFIRM = "/v2/payment-intents/{payment_intent_id}/confirm"
    V2_TRANSFERBATCHES = "/v2/transfer-batches"
    V2_TRANSFERBATCHES_TRANSFER_BATCH_ID = "/v2/transfer-batches/{transfer_batch_id}"
    V2_PAYMENTCUSTOMERS = "/v2/payment-customers"
    V2_PAYMENTCUSTOMERS_PAYMENT_CUSTOMER_ID = "/v2/payment-customers/{payment_customer_id}"
    V2_CHECKOUTSESSIONS = "/v2/checkout-sessions"
    V2_CHECKOUTSESSIONS_CHECKOUT_SESSION_ID = "/v2/checkout-sessions/{checkout_session_id}"
    V2_APPS = "/v2/apps"
    V2_APPS_APP_ID = "/v2/apps/{app_id}"
    V2_APPS_APP_ID_COMPLIANCE = "/v2/apps/{app_id}/compliance"
    V2_APPS_APP_ID_ACHACCOUNT = "/v2/apps/{app_id}/ach-account"
    V2_APPS_APP_ID_DEPOSIT = "/v2/apps/{app_id}/deposit"
    V2_APPS_APP_ID_WITHDRAW = "/v2/apps/{app_id}/withdraw"
    V2_PAYMENTMETHODS = "/v2/payment-methods"
    V2_PAYMENTMETHODS_PAYMENT_METHOD_ID = "/v2/payment-methods/{payment_method_id}"
    V2_PAYMENTMETHODS_PAYMENT_METHOD_ID_ATTACH = "/v2/payment-methods/{payment_method_id}/attach"
    V2_PAYMENTMETHODS_PAYMENT_METHOD_ID_DETACH = "/v2/payment-methods/{payment_method_id}/detach"
    V2_DISPUTES = "/v2/disputes"
    V2_DISPUTES_DISPUTE_ID = "/v2/disputes/{dispute_id}"
    V2_DISPUTES_DISPUTE_ID_EVIDENCE = "/v2/disputes/{dispute_id}/evidence"
    V2_DISPUTES_DISPUTE_ID_SUBMIT = "/v2/disputes/{dispute_id}/submit"
    V2_REFUNDS = "/v2/refunds"
    V2_REFUNDS_REFUND_ID = "/v2/refunds/{refund_id}"
    V2_ORGANIZATIONTRANSFERS = "/v2/organization-transfers"
    V2_ORGANIZATIONTRANSFERS_TRANSFER_ID = "/v2/organization-transfers/{transfer_id}"
