# coding: utf-8

"""
    dots api

    Scalable and Flexible Payouts Infrastructure

    The version of the OpenAPI document: 1.0
    Contact: info@dots.dev
    Created by: https://dots.dev
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from dots_python_sdk import schemas  # noqa: F401


class UsersSubmitComplianceInfoRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def w9() -> typing.Type['UsersSubmitComplianceInfoRequestW9']:
                return UsersSubmitComplianceInfoRequestW9
        
            @staticmethod
            def w8ben() -> typing.Type['UsersSubmitComplianceInfoRequestW8Ben']:
                return UsersSubmitComplianceInfoRequestW8Ben
            __annotations__ = {
                "w9": w9,
                "w8ben": w8ben,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["w9"]) -> 'UsersSubmitComplianceInfoRequestW9': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["w8ben"]) -> 'UsersSubmitComplianceInfoRequestW8Ben': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["w9", "w8ben", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["w9"]) -> typing.Union['UsersSubmitComplianceInfoRequestW9', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["w8ben"]) -> typing.Union['UsersSubmitComplianceInfoRequestW8Ben', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["w9", "w8ben", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        w9: typing.Union['UsersSubmitComplianceInfoRequestW9', schemas.Unset] = schemas.unset,
        w8ben: typing.Union['UsersSubmitComplianceInfoRequestW8Ben', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'UsersSubmitComplianceInfoRequest':
        return super().__new__(
            cls,
            *args,
            w9=w9,
            w8ben=w8ben,
            _configuration=_configuration,
            **kwargs,
        )

from dots_python_sdk.model.users_submit_compliance_info_request_w8_ben import UsersSubmitComplianceInfoRequestW8Ben
from dots_python_sdk.model.users_submit_compliance_info_request_w9 import UsersSubmitComplianceInfoRequestW9
