# coding: utf-8

"""
    dots api

    Scalable and Flexible Payouts Infrastructure

    The version of the OpenAPI document: 1.0
    Contact: info@dots.dev
    Created by: https://dots.dev
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from dots_python_sdk import schemas  # noqa: F401


class UsersSubmitComplianceInfoRequestW8BenAddress(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Address of the user or their business.
    """


    class MetaOapg:
        required = {
            "line_1",
            "country",
            "city",
            "postcode",
            "state",
        }
        
        class properties:
            line_1 = schemas.StrSchema
            city = schemas.StrSchema
            state = schemas.StrSchema
            country = schemas.StrSchema
            postcode = schemas.StrSchema
            line_2 = schemas.StrSchema
            __annotations__ = {
                "line_1": line_1,
                "city": city,
                "state": state,
                "country": country,
                "postcode": postcode,
                "line_2": line_2,
            }
    
    line_1: MetaOapg.properties.line_1
    country: MetaOapg.properties.country
    city: MetaOapg.properties.city
    postcode: MetaOapg.properties.postcode
    state: MetaOapg.properties.state
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["line_1"]) -> MetaOapg.properties.line_1: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["city"]) -> MetaOapg.properties.city: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["state"]) -> MetaOapg.properties.state: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["country"]) -> MetaOapg.properties.country: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["postcode"]) -> MetaOapg.properties.postcode: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["line_2"]) -> MetaOapg.properties.line_2: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["line_1", "city", "state", "country", "postcode", "line_2", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["line_1"]) -> MetaOapg.properties.line_1: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["city"]) -> MetaOapg.properties.city: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["state"]) -> MetaOapg.properties.state: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["country"]) -> MetaOapg.properties.country: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["postcode"]) -> MetaOapg.properties.postcode: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["line_2"]) -> typing.Union[MetaOapg.properties.line_2, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["line_1", "city", "state", "country", "postcode", "line_2", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        line_1: typing.Union[MetaOapg.properties.line_1, str, ],
        country: typing.Union[MetaOapg.properties.country, str, ],
        city: typing.Union[MetaOapg.properties.city, str, ],
        postcode: typing.Union[MetaOapg.properties.postcode, str, ],
        state: typing.Union[MetaOapg.properties.state, str, ],
        line_2: typing.Union[MetaOapg.properties.line_2, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'UsersSubmitComplianceInfoRequestW8BenAddress':
        return super().__new__(
            cls,
            *args,
            line_1=line_1,
            country=country,
            city=city,
            postcode=postcode,
            state=state,
            line_2=line_2,
            _configuration=_configuration,
            **kwargs,
        )
