# coding: utf-8

"""
    dots api

    Scalable and Flexible Payouts Infrastructure

    The version of the OpenAPI document: 1.0
    Contact: info@dots.dev
    Created by: https://dots.dev
"""

from dots_python_sdk.paths.v2_apps_app_id_ach_account.put import AddAchAccount
from dots_python_sdk.paths.v2_apps.post import CreateNewApp
from dots_python_sdk.paths.v2_apps_app_id_deposit.post import DepositFunds
from dots_python_sdk.paths.v2_apps_app_id_ach_account.get import GetAchAccount
from dots_python_sdk.paths.v2_apps_app_id.get import GetById
from dots_python_sdk.paths.v2_apps_app_id_compliance.get import GetComplianceInfo
from dots_python_sdk.paths.v2_apps.get import ListAll
from dots_python_sdk.paths.v2_apps_app_id_compliance.put import UpdateComplianceInfo
from dots_python_sdk.paths.v2_apps_app_id_withdraw.post import WithdrawFunds
from dots_python_sdk.apis.tags.apps_api_raw import AppsApiRaw


class AppsApi(
    AddAchAccount,
    CreateNewApp,
    DepositFunds,
    GetAchAccount,
    GetById,
    GetComplianceInfo,
    ListAll,
    UpdateComplianceInfo,
    WithdrawFunds,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: AppsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = AppsApiRaw(api_client)
