# coding: utf-8

"""
    dots api

    Scalable and Flexible Payouts Infrastructure

    The version of the OpenAPI document: 1.0
    Contact: info@dots.dev
    Created by: https://dots.dev
"""

from dots_python_sdk.paths.v2_apps_app_id_ach_account.put import AddAchAccountRaw
from dots_python_sdk.paths.v2_apps.post import CreateNewAppRaw
from dots_python_sdk.paths.v2_apps_app_id_deposit.post import DepositFundsRaw
from dots_python_sdk.paths.v2_apps_app_id_ach_account.get import GetAchAccountRaw
from dots_python_sdk.paths.v2_apps_app_id.get import GetByIdRaw
from dots_python_sdk.paths.v2_apps_app_id_compliance.get import GetComplianceInfoRaw
from dots_python_sdk.paths.v2_apps.get import ListAllRaw
from dots_python_sdk.paths.v2_apps_app_id_compliance.put import UpdateComplianceInfoRaw
from dots_python_sdk.paths.v2_apps_app_id_withdraw.post import WithdrawFundsRaw


class AppsApiRaw(
    AddAchAccountRaw,
    CreateNewAppRaw,
    DepositFundsRaw,
    GetAchAccountRaw,
    GetByIdRaw,
    GetComplianceInfoRaw,
    ListAllRaw,
    UpdateComplianceInfoRaw,
    WithdrawFundsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
