# coding: utf-8

"""
    dots api

    Scalable and Flexible Payouts Infrastructure

    The version of the OpenAPI document: 1.0
    Contact: info@dots.dev
    Created by: https://dots.dev
"""

from dots_python_sdk.paths.v2_checkout_sessions.post import CreateSession
from dots_python_sdk.paths.v2_checkout_sessions_checkout_session_id.get import GetById
from dots_python_sdk.paths.v2_checkout_sessions.get import ListAll
from dots_python_sdk.apis.tags.checkout_sessions_api_raw import CheckoutSessionsApiRaw


class CheckoutSessionsApi(
    CreateSession,
    GetById,
    ListAll,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: CheckoutSessionsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = CheckoutSessionsApiRaw(api_client)
