# coding: utf-8

"""
    dots api

    Scalable and Flexible Payouts Infrastructure

    The version of the OpenAPI document: 1.0
    Contact: info@dots.dev
    Created by: https://dots.dev
"""

from dots_python_sdk.paths.v2_disputes_dispute_id_evidence.post import AddEvidenceFileRaw
from dots_python_sdk.paths.v2_disputes.get import GetAllRaw
from dots_python_sdk.paths.v2_disputes_dispute_id.get import GetByIdRaw
from dots_python_sdk.paths.v2_disputes_dispute_id_submit.post import SubmitDisputeRaw


class DisputesApiRaw(
    AddEvidenceFileRaw,
    GetAllRaw,
    GetByIdRaw,
    SubmitDisputeRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
