# coding: utf-8

"""
    dots api

    Scalable and Flexible Payouts Infrastructure

    The version of the OpenAPI document: 1.0
    Contact: info@dots.dev
    Created by: https://dots.dev
"""

from dots_python_sdk.paths.v2_flows.post import CreateNewFlow
from dots_python_sdk.paths.v2_flows_flow_id.get import GetById
from dots_python_sdk.paths.v2_flows.get import ListAll
from dots_python_sdk.apis.tags.flows_api_raw import FlowsApiRaw


class FlowsApi(
    CreateNewFlow,
    GetById,
    ListAll,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: FlowsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = FlowsApiRaw(api_client)
