# coding: utf-8

"""
    dots api

    Scalable and Flexible Payouts Infrastructure

    The version of the OpenAPI document: 1.0
    Contact: info@dots.dev
    Created by: https://dots.dev
"""

from dots_python_sdk.paths.v2_payment_customers.post import CreateCustomer
from dots_python_sdk.paths.v2_payment_customers_payment_customer_id.get import GetById
from dots_python_sdk.paths.v2_payment_customers.get import ListAll
from dots_python_sdk.apis.tags.payment_customers_api_raw import PaymentCustomersApiRaw


class PaymentCustomersApi(
    CreateCustomer,
    GetById,
    ListAll,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: PaymentCustomersApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = PaymentCustomersApiRaw(api_client)
