# coding: utf-8

"""
    dots api

    Scalable and Flexible Payouts Infrastructure

    The version of the OpenAPI document: 1.0
    Contact: info@dots.dev
    Created by: https://dots.dev
"""

from dots_python_sdk.paths.v2_payment_intents_payment_intent_id_confirm.post import ConfirmIntentRaw
from dots_python_sdk.paths.v2_payment_intents.post import CreateIntentRaw
from dots_python_sdk.paths.v2_payment_intents_payment_intent_id.get import GetByIdRaw
from dots_python_sdk.paths.v2_payment_intents.get import ListAllRaw


class PaymentIntentsApiRaw(
    ConfirmIntentRaw,
    CreateIntentRaw,
    GetByIdRaw,
    ListAllRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
