# coding: utf-8

"""
    dots api

    Scalable and Flexible Payouts Infrastructure

    The version of the OpenAPI document: 1.0
    Contact: info@dots.dev
    Created by: https://dots.dev
"""

from dots_python_sdk.paths.v2_payment_customers.post import CreateCustomerRaw
from dots_python_sdk.paths.v2_payment_customers_payment_customer_id.get import GetByIdRaw
from dots_python_sdk.paths.v2_payment_customers.get import ListAllRaw


class PaymentCustomersApiRaw(
    CreateCustomerRaw,
    GetByIdRaw,
    ListAllRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
