# coding: utf-8

"""
    dots api

    Scalable and Flexible Payouts Infrastructure

    The version of the OpenAPI document: 1.0
    Contact: info@dots.dev
    Created by: https://dots.dev
"""

from dots_python_sdk.paths.v2_payment_intents_payment_intent_id_confirm.post import ConfirmIntent
from dots_python_sdk.paths.v2_payment_intents.post import CreateIntent
from dots_python_sdk.paths.v2_payment_intents_payment_intent_id.get import GetById
from dots_python_sdk.paths.v2_payment_intents.get import ListAll
from dots_python_sdk.apis.tags.payment_intents_api_raw import PaymentIntentsApiRaw


class PaymentIntentsApi(
    ConfirmIntent,
    CreateIntent,
    GetById,
    ListAll,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: PaymentIntentsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = PaymentIntentsApiRaw(api_client)
