# coding: utf-8

"""
    dots api

    Scalable and Flexible Payouts Infrastructure

    The version of the OpenAPI document: 1.0
    Contact: info@dots.dev
    Created by: https://dots.dev
"""

from dots_python_sdk.paths.v2_payment_methods_payment_method_id_attach.post import AttachPaymentMethod
from dots_python_sdk.paths.v2_payment_methods_payment_method_id_detach.post import DetachPaymentMethod
from dots_python_sdk.paths.v2_payment_methods_payment_method_id.get import GetById
from dots_python_sdk.paths.v2_payment_methods.get import ListAllPaymentCustomer
from dots_python_sdk.apis.tags.payment_methods_api_raw import PaymentMethodsApiRaw


class PaymentMethodsApi(
    AttachPaymentMethod,
    DetachPaymentMethod,
    GetById,
    ListAllPaymentCustomer,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: PaymentMethodsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = PaymentMethodsApiRaw(api_client)
