# coding: utf-8

"""
    dots api

    Scalable and Flexible Payouts Infrastructure

    The version of the OpenAPI document: 1.0
    Contact: info@dots.dev
    Created by: https://dots.dev
"""

from dots_python_sdk.paths.v2_payments.post import CreateTransaction
from dots_python_sdk.apis.tags.payments_api_raw import PaymentsApiRaw


class PaymentsApi(
    CreateTransaction,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: PaymentsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = PaymentsApiRaw(api_client)
