# coding: utf-8

"""
    dots api

    Scalable and Flexible Payouts Infrastructure

    The version of the OpenAPI document: 1.0
    Contact: info@dots.dev
    Created by: https://dots.dev
"""

from dots_python_sdk.paths.v2_payouts.post import CreatePayoutRaw
from dots_python_sdk.paths.v2_payouts_send_payout.post import SendPayoutRaw


class PayoutsApiRaw(
    CreatePayoutRaw,
    SendPayoutRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
