# coding: utf-8

"""
    dots api

    Scalable and Flexible Payouts Infrastructure

    The version of the OpenAPI document: 1.0
    Contact: info@dots.dev
    Created by: https://dots.dev
"""

from dots_python_sdk.paths.v2_payout_requests.get import GetAllPayouts
from dots_python_sdk.paths.v2_payout_requests_payout_request_id.get import GetPayoutById
from dots_python_sdk.paths.v2_payout_requests.post import SubmitRequest
from dots_python_sdk.apis.tags.payout_requests_api_raw import PayoutRequestsApiRaw


class PayoutRequestsApi(
    GetAllPayouts,
    GetPayoutById,
    SubmitRequest,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: PayoutRequestsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = PayoutRequestsApiRaw(api_client)
