# coding: utf-8

"""
    dots api

    Scalable and Flexible Payouts Infrastructure

    The version of the OpenAPI document: 1.0
    Contact: info@dots.dev
    Created by: https://dots.dev
"""

from dots_python_sdk.paths.v2_payout_links_payout_link_id.delete import CancelLink
from dots_python_sdk.paths.v2_payout_links.post import CreatePayoutLink
from dots_python_sdk.paths.v2_payout_links_payout_link_id.get import GetPayoutLink
from dots_python_sdk.paths.v2_payout_links.get import ListAll
from dots_python_sdk.apis.tags.payout_links_api_raw import PayoutLinksApiRaw


class PayoutLinksApi(
    CancelLink,
    CreatePayoutLink,
    GetPayoutLink,
    ListAll,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: PayoutLinksApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = PayoutLinksApiRaw(api_client)
