# coding: utf-8

"""
    dots api

    Scalable and Flexible Payouts Infrastructure

    The version of the OpenAPI document: 1.0
    Contact: info@dots.dev
    Created by: https://dots.dev
"""

from dots_python_sdk.paths.v2_payout_requests.get import GetAllPayoutsRaw
from dots_python_sdk.paths.v2_payout_requests_payout_request_id.get import GetPayoutByIdRaw
from dots_python_sdk.paths.v2_payout_requests.post import SubmitRequestRaw


class PayoutRequestsApiRaw(
    GetAllPayoutsRaw,
    GetPayoutByIdRaw,
    SubmitRequestRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
