# coding: utf-8

"""
    dots api

    Scalable and Flexible Payouts Infrastructure

    The version of the OpenAPI document: 1.0
    Contact: info@dots.dev
    Created by: https://dots.dev
"""

from dots_python_sdk.paths.v2_payout_links_payout_link_id.delete import CancelLinkRaw
from dots_python_sdk.paths.v2_payout_links.post import CreatePayoutLinkRaw
from dots_python_sdk.paths.v2_payout_links_payout_link_id.get import GetPayoutLinkRaw
from dots_python_sdk.paths.v2_payout_links.get import ListAllRaw


class PayoutLinksApiRaw(
    CancelLinkRaw,
    CreatePayoutLinkRaw,
    GetPayoutLinkRaw,
    ListAllRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
