# coding: utf-8

"""
    dots api

    Scalable and Flexible Payouts Infrastructure

    The version of the OpenAPI document: 1.0
    Contact: info@dots.dev
    Created by: https://dots.dev
"""

from dots_python_sdk.paths.v2_refunds.post import CreateRefundRaw
from dots_python_sdk.paths.v2_refunds.get import GetAllRaw
from dots_python_sdk.paths.v2_refunds_refund_id.get import GetByIdRaw


class RefundsApiRaw(
    CreateRefundRaw,
    GetAllRaw,
    GetByIdRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
