# coding: utf-8

"""
    dots api

    Scalable and Flexible Payouts Infrastructure

    The version of the OpenAPI document: 1.0
    Contact: info@dots.dev
    Created by: https://dots.dev
"""

from dots_python_sdk.paths.v2_refunds.post import CreateRefund
from dots_python_sdk.paths.v2_refunds.get import GetAll
from dots_python_sdk.paths.v2_refunds_refund_id.get import GetById
from dots_python_sdk.apis.tags.refunds_api_raw import RefundsApiRaw


class RefundsApi(
    CreateRefund,
    GetAll,
    GetById,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: RefundsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = RefundsApiRaw(api_client)
