# coding: utf-8

"""
    dots api

    Scalable and Flexible Payouts Infrastructure

    The version of the OpenAPI document: 1.0
    Contact: info@dots.dev
    Created by: https://dots.dev
"""

from dots_python_sdk.paths.v2_transactions_transaction_id.get import GetByIdRaw
from dots_python_sdk.paths.v2_transactions.get import ListAllRaw


class TransactionsApiRaw(
    GetByIdRaw,
    ListAllRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
