# coding: utf-8

"""
    dots api

    Scalable and Flexible Payouts Infrastructure

    The version of the OpenAPI document: 1.0
    Contact: info@dots.dev
    Created by: https://dots.dev
"""

from dots_python_sdk.paths.v2_transfer_batches.post import CreateBatch
from dots_python_sdk.paths.v2_transfer_batches_transfer_batch_id.get import GetById
from dots_python_sdk.paths.v2_transfer_batches.get import ListAll
from dots_python_sdk.apis.tags.transfer_batches_api_raw import TransferBatchesApiRaw


class TransferBatchesApi(
    CreateBatch,
    GetById,
    ListAll,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: TransferBatchesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = TransferBatchesApiRaw(api_client)
