# coding: utf-8

"""
    dots api

    Scalable and Flexible Payouts Infrastructure

    The version of the OpenAPI document: 1.0
    Contact: info@dots.dev
    Created by: https://dots.dev
"""

from dots_python_sdk.paths.v2_organization_transfers.post import CreateOrganizationTransferRaw
from dots_python_sdk.paths.v2_transfers.post import CreateTransferRaw
from dots_python_sdk.paths.v2_organization_transfers.get import GetAllRaw
from dots_python_sdk.paths.v2_transfers_transfer_id.get import GetByIdRaw
from dots_python_sdk.paths.v2_organization_transfers_transfer_id.get import GetById0Raw
from dots_python_sdk.paths.v2_transfers.get import ListAllRaw


class TransfersApiRaw(
    CreateOrganizationTransferRaw,
    CreateTransferRaw,
    GetAllRaw,
    GetByIdRaw,
    GetById0Raw,
    ListAllRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
