# coding: utf-8

"""
    dots api

    Scalable and Flexible Payouts Infrastructure

    The version of the OpenAPI document: 1.0
    Contact: info@dots.dev
    Created by: https://dots.dev
"""

from dots_python_sdk.paths.v2_transfer_batches.post import CreateBatchRaw
from dots_python_sdk.paths.v2_transfer_batches_transfer_batch_id.get import GetByIdRaw
from dots_python_sdk.paths.v2_transfer_batches.get import ListAllRaw


class TransferBatchesApiRaw(
    CreateBatchRaw,
    GetByIdRaw,
    ListAllRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
