# coding: utf-8

"""
    dots api

    Scalable and Flexible Payouts Infrastructure

    The version of the OpenAPI document: 1.0
    Contact: info@dots.dev
    Created by: https://dots.dev
"""

from dots_python_sdk.paths.v2_users_user_id_payout_methods.put import AddPayoutMethodRaw
from dots_python_sdk.paths.v2_users.post import CreateNewUserRaw
from dots_python_sdk.paths.v2_users_user_id.get import GetUserByIdRaw
from dots_python_sdk.paths.v2_users.get import ListAllUsersRaw
from dots_python_sdk.paths.v2_users_user_id_payout_methods.get import ListPayoutMethodsRaw
from dots_python_sdk.paths.v2_users_user_id.delete import RemoveUserRaw
from dots_python_sdk.paths.v2_users_user_id_send_verification_token.post import SendVerificationTokenRaw
from dots_python_sdk.paths.v2_users_user_id_compliance.put import SubmitComplianceInfoRaw
from dots_python_sdk.paths.v2_users_user_id.patch import UpdateUserObjectRaw
from dots_python_sdk.paths.v2_users_user_id_verify.post import VerifyUserTokenRaw


class UsersApiRaw(
    AddPayoutMethodRaw,
    CreateNewUserRaw,
    GetUserByIdRaw,
    ListAllUsersRaw,
    ListPayoutMethodsRaw,
    RemoveUserRaw,
    SendVerificationTokenRaw,
    SubmitComplianceInfoRaw,
    UpdateUserObjectRaw,
    VerifyUserTokenRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
