# coding: utf-8

"""
    dots api

    Scalable and Flexible Payouts Infrastructure

    The version of the OpenAPI document: 1.0
    Contact: info@dots.dev
    Created by: https://dots.dev
"""

from dots_python_sdk.paths.v2_users_user_id_payout_methods.put import AddPayoutMethod
from dots_python_sdk.paths.v2_users.post import CreateNewUser
from dots_python_sdk.paths.v2_users_user_id.get import GetUserById
from dots_python_sdk.paths.v2_users.get import ListAllUsers
from dots_python_sdk.paths.v2_users_user_id_payout_methods.get import ListPayoutMethods
from dots_python_sdk.paths.v2_users_user_id.delete import RemoveUser
from dots_python_sdk.paths.v2_users_user_id_send_verification_token.post import SendVerificationToken
from dots_python_sdk.paths.v2_users_user_id_compliance.put import SubmitComplianceInfo
from dots_python_sdk.paths.v2_users_user_id.patch import UpdateUserObject
from dots_python_sdk.paths.v2_users_user_id_verify.post import VerifyUserToken
from dots_python_sdk.apis.tags.users_api_raw import UsersApiRaw


class UsersApi(
    AddPayoutMethod,
    CreateNewUser,
    GetUserById,
    ListAllUsers,
    ListPayoutMethods,
    RemoveUser,
    SendVerificationToken,
    SubmitComplianceInfo,
    UpdateUserObject,
    VerifyUserToken,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: UsersApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = UsersApiRaw(api_client)
